version: "3.9"

services:
  localstack:
    image: localstack/localstack:1.2.0
    ports:
      - "4566:4566"   # LocalStack Edge Proxy
    environment:
      - SERVICES=sns,sqs
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-2
    container_name: localstack
    volumes:
      - "./localstack-init:/docker-entrypoint-initaws.d"
      - "/var/run/docker.sock:/var/run/docker.sock"