server:
  port: 9090

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
    stack:
      auto: false

    sqs:
      end-point: http://localhost:4566
      any-sqs:
        name: PULLED-EVENTS-RECEIVED-DEV
        url: http://localhost:4566/000000000000/PULLED-EVENTS-RECEIVED-DEV
      any-sqs-2:
        name: any-sqs2
        url: http://localhost:4566/000000000000/any-sqs2
      any-sqs-fifo:
        name: ANY-SQS.fifo
        url: http://localhost:4566/000000000000/ANY-SQS.fifo

    sns:
      end-point: http://localhost:4566
      any-sns:
        topic-arn: arn:aws:sns:ap-northeast-2:000000000000:any-sns